name: belem
channels: [conda-forge]
dependencies:
  - python=3.11
  - pip
  - pip:
      - eclipse-sumo==1.27.1
      - sumo-rl
      - stable-baselines3[extra]>=2.0.0
      - optuna
      - optuna-dashboard
      - pandas
      - matplotlib
      - seaborn
      - tensorboard